--[VLLL] Sequence :순차번호 생성기 . 대부분 인위적인 pk 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    START WITH 1  --1부터시작
    INCREMENT BY 1 --1씩 증가
    MAXVALUE 9999   --최대값
    MINVALUE  1     --최소값
    NOCACHE
    NOCYCLE;
    SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; --다음 순차번호 생성
    SELECT FRIEND_SEQ.CURRVAL FROM DUAL; -- 횬재 시퀀스의 값
    DROP SEQUENCE FRIEND_SEQ;
    
    CREATE TABLE FRIEND (
    NO NUMBER(5)PRIMARY KEY, --시퀀스를 사용해서 값이 들어갈 필드
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE, --NULL 허용, NULL이 아니면 유일한 값
    ADDRESS VARCHAR2(255),
    LAST_MODIFY DATE DEFAULT SYSDATE
    );
    INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS) 
  VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', NULL, '서울 서대문'); -- 몇번 실행 
SELECT * FROM FRIEND;
--INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
--  VALUES (FRIEND_SEQ.NEXTVAL, NULL, '010-9999-9999','서울 마포'); -- 에러(NOT NULL)
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
  VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999','서울 마포');  
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
  VALUES (FRIEND_SEQ.NEXTVAL, '신길동', '010-9999-9999','서울 영등포'); -- 에러(UNIQUE)
INSERT INTO FRIEND (NO, NAME, TEL, ADDRESS)
  VALUES (FRIEND_SEQ.NEXTVAL, '신길동', '010-8888-9999','서울 영등포');
SELECT * FROM FRIEND;
 -- ex. 초기값 101부터 최대값 999,999까지 1씩 증가하는 TEST_SEQ 시퀀스를 생성하고 시퀀스를 사용하시오
CREATE SEQUENCE TEST_SEQ 
  START WITH 101
  MAXVALUE 999999
  NOCACHE
  NOCYCLE;
SELECT TEST_SEQ.CURRVAL FROM DUAL; -- 시퀀스 사용전에는 현재값을 조회할 수 없음
SELECT TEST_SEQ.NEXTVAL FROM DUAL; -- 시퀀스 사용   
--ex.시퀀스 no_SEQ초기값 1부터 999까지 1씩 증가하는 사용:
--SYSDATE의 'RRMMDD' 추출=>'230728' || 시퀀스 생성 수 (3)->'003' =>'230728001'
DROP SEQUENCE NO_SEQ;
CREATE SEQUENCE NO_SEQ MAXVALUE 999 NOCACHE NOCYCLE ;
SELECT TO_CHAR(SYSDATE, 'RRMMDD') FROM DUAL;    --'230728'
SELECT TO_CHAR(NO_SEQ.NEXTVAL, '000') FROM DUAL; --'005'
SELECT TO_CHAR(SYSDATE, 'RRMMDD') || TO_CHAR(NO_SEQ.NEXTVAL, '000')FROM DUAL; --'230728 005'
SELECT TO_CHAR(SYSDATE, 'RRMMDD') ||TRIM(TO_CHAR(NO_SEQ.NEXTVAL, '000'))NO FROM DUAL; --'230728005'
--------------
DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;

CREATE TABLE MEMBER_LEVEL(
  LEVELNO NUMBER(10) PRIMARY KEY,
  LEVELNAME VARCHAR2(10) NOT NULL
);
CREATE TABLE MEMBER (
  mNO    NUMBER(10) PRIMARY KEY,
  mNAME  VARCHAR2(10) NOT NULL,
  mPW    VARCHAR2(10) CHECK(LENGTH(mPW) BETWEEN 1 AND 8),-- VARCHAR2(8) not null
  mEMAIL VARCHAR2(50) UNIQUE,
  mPOINT NUMBER(10) CHECK(mPOINT>=0),
  mRDATE DATE DEFAULT SYSDATE,
  LEVELNO NUMBER(10) REFERENCES MEMBER_LEVEL(LEVELNO)
);
 CREATE SEQUENCE MEMBER_MNO_SQ
  START WITH 1
  MAXVALUE 999 
  NOCACHE NOCYCLE;
  DROP SEQUENCE MEMBER_MNO_SQ;
 SELECT MEMBER_MNO_SQ.NEXTVAL FROM DUAL;
 SELECT MEMBER_MNO_SQ.CURRVAL FROM DUAL;

 
 INSERT INTO MEMBER_LEVEL(LEVELNO,LEVELNAME) VALUES (-1 , 'black'); 
 INSERT INTO MEMBER_LEVEL(LEVELNO,LEVELNAME) VALUES (0 , '일반');
 INSERT INTO MEMBER_LEVEL(LEVELNO,LEVELNAME) VALUES (1 , '실버');
 INSERT INTO MEMBER_LEVEL(LEVELNO,LEVELNAME) VALUES (2 , '골드'); 
 INSERT INTO MEMBER (mNO,mNAME,mPW,mEMAIL,mPOINT,mRDATE,LEVELNO) 
    VALUES (MEMBER_MNO_SQ.NEXTVAL, '홍길동' ,'aa','hong@hong.com',0 ,'22/03/10', 0);
 INSERT INTO MEMBER (mNO,mNAME,mPW,mEMAIL,mPOINT,mRDATE,LEVELNO) 
    VALUES (MEMBER_MNO_SQ.NEXTVAL, '신길동' ,'bb','sin@sin.com',1000 ,'22/04/01', 1);
   
 SELECT*FROM MEMBER_LEVEL; 
 SELECT mNO "mNO", mNAME "mNAME", TO_CHAR(mRDATE ,'YYYY-MM-DD') "mRDATE" , mEMAIL "mEMAIL", mPOINT "point", LEVELNAME "levelname" 
  FROM MEMBER M, MEMBER_LEVEL L 
  WHERE M.LEVELNO = L.LEVELNO;
  SELECT * FROM MEMBER_LEVEL;
  
------------------
DROP TABLE CART;
DROP TABLE ORDERDETAIL;
DROP TABLE ORDERS;
DROP TABLE MEMBERS;
DROP TABLE PRODUCT;

CREATE TABLE MEMBERS (
  mID    VARCHAR2(5)PRIMARY KEY ,
 mNAME   VARCHAR2(10) NOT NULL,
 mADRESS VARCHAR2(200),  
 mTEL    VARCHAR2(11) ,
 mEMAIL  VARCHAR2(30) NOT NULL
);
CREATE TABLE PRODUCT (
  pCODE  VARCHAR2(5) PRIMARY KEY,
  pNAME  VARCHAR2(20) NOT NULL,
  pPRICE  NUMBER(10)  CHECK(pPRICE>=100),
  STOCK   NUMBER(10)
);
CREATE TABLE CART (
  cNO    NUMBER(3) PRIMARY KEY,
  mID    VARCHAR2(5) REFERENCES MEMBERS(mID) ,
  pCODE  VARCHAR2(5) REFERENCES PRODUCT(pCODE),
  QTY    NUMBER(10) ,
  COST   NUMBER(20) NOT NULL
);
CREATE TABLE ORDERS (
 oNO     NUMBER(9)  PRIMARY KEY ,
 mID     VARCHAR2(5) REFERENCES MEMBERS(mID),
 oDATE   DATE       DEFAULT SYSDATE,
 oNAME   VARCHAR2(10) NOT NULL,
 oADRESS VARCHAR2(200) NOT NULL,
 oTEL    NUMBER(11)  NOT NULL
);
CREATE TABLE ORDERDETAIL (
 NO     NUMBER(5) PRIMARY KEY,
 oNO    NUMBER(9) REFERENCES ORDERS(oNO),
 pCODE  VARCHAR2(5) REFERENCES PRODUCT(pCODE) ,
 QTY    NUMBER(10),
 COST   NUMBER(20) NOT NULL
 );
 DROP SEQUENCE CART_NO_SQ;
 DROP SEQUENCE ORDERS_NO_SQ;
 DROP SEQUENCE DETIL_NO_SQ;
CREATE SEQUENCE CART_NO_SQ MAXVALUE 999 NOCACHE NOCYCLE ;
CREATE SEQUENCE ORDERS_NO_SQ MAXVALUE 999999999;
CREATE SEQUENCE DETIL_NO_SQ MAXVALUE 99999;

SELECT * FROM MEMBERS;
SELECT * FROM PRODUCT;
SELECT * FROM CART;
INSERT INTO MEMBERS VALUES ('adc','홍길동','서울시 서대문구 대현동',01099999999,'hong@hong.com');
INSERT INTO MEMBERS VALUES ('def','김길동','경기도 수원시',01088888888,'kim@gil.com');
INSERT INTO PRODUCT(pCODE,pNAME,pPRICE)VALUES ('A1','맥주',3000);  
INSERT INTO PRODUCT(pCODE,pNAME,pPRICE)VALUES ('A2','마스크',200); 
INSERT INTO PRODUCT(pCODE,pNAME,pPRICE )VALUES ('B1','땅콩',3000);
INSERT INTO PRODUCT(pCODE,pNAME,pPRICE)VALUES ('B2','오징어',5000);
INSERT INTO PRODUCT(pCODE,pNAME,pPRICE)VALUES ('C1','소독약',7000);
SELECT * FROM MEMBERS;
SELECT * FROM PRODUCT;
COMMIT;
SELECT TO_CHAR(SYSDATE,'RRMMDD')||TRIM(TO_CHAR(ORDERS_NO_SQ.NEXTVAL ,'000'));

INSERT INTO CART VALUES
  (CART_no_sq.NEXTVAL, 'adc', 'A1', 3, (SELECT pPRICE FROM PRODUCT WHERE PCODE='A1')*3); 
INSERT INTO CART VALUES(CART_no_sq.NEXTVAL,'DEF','B2',2,(SELECT pPRICE FROM PRODUCT WHERE PCODE='b1')*2);

INSERT INTO CART VALUES('DEF','C1',1,7000);
INSERT INTO CART VALUES('ABC','A1',2,6000);
INSERT INTO CART VALUES('ABC','B1',1,3000);
INSERT INTO CART VALUES(CART_NO_SQ.NEXTVAL,'abc','C1',1,7000);
INSERT INTO ORDERS VALUES(ORDERS_NO_SQ.NEXTVAL, 'abc', '2023/07/26', '홍길동', '서울시 서대문구 대현동', 01099999999);
INSERT INTO ORDERS VALUES( 'DEF','2023/07/26','김길동','경기도 수원시',01088888888);
INSERT INTO ORDERS VALUES(ORDERS_NO_SQ.NEXTVAL,'ABC','2023/07/26','홍아빠','제주도 제주시',01077779999);
INSERT








