--[x]view,in-line view, top-n★
DROP TABLE EMP1;
CREATE TABLE EMP1 AS SELECT EMPNO,ENAME, JOB, MGR, HIREDATE, DEPTNO FROM EMP;
SELECT * FROM EMP1; --타부서에서 권한을 줄 테이블(타부서에서는 검색, 추가, 삭제 수정)
SELECT * FROM USER_TABLES WHERE TABLE_NAME LIKE 'EMP%';
INSERT INTO EMP1 (EMPNO,ENAME,DEPTNO) VALUES (1111,'홍',30);
SELECT * FROM EMP1;--홍검색
SELECT * FROM EMP;
DROP TABLE EMP1;
--1.VIEW : 가상의 테이블 (1)단순뷰 (2)복합뷰
--(1)단순뷰 :하나의 테이블을 이용해서 만든 뷰 (가상의 테이블: 물리적인 저장공간과 데이터가 따로 없음 )
CREATE OR REPLACE VIEW EMPvO  --EMP테이블에서 특정필드만 VIEW로 생성
    AS SELECT EMPNO,ENAME, JOB, MGR, HIREDATE, DEPTNO FROM EMP;
SELECT * FROM EMPvO;
SELECT * FROM EMP;
SELECT * FROM USER_TABLES WHERE TABLE_NAME LIKE 'EMP%';
SELECT * FROM USER_VIEWS;
INSERT INTO EMPvO VALUES (1111,'홍','MANAGER',NULL,SYSDATE,40) ;--뷰에 INSERT 
SELECT * FROM EMPvO;
SELECT * FROM EMP;
ROLLBACK;

CREATE OR REPLACE VIEW EMPvO --EMP테이블에서 특정 행(ROW)만 뷰로 생성
    AS SELECT * FROM EMP WHERE DEPTNO=30;
 SELECT * FROM EMPvO;
 INSERT INTO EMPvO VALUES(1111,'홍','MANAGER',NULL,SYSDATE,NULL,NULL,30);
 SELECT * FROM EMPvO;
 SELECT * FROM EMP WHERE EMPNO<2000;
 INSERT INTO EMPvO (EMPNO, ENAME, DEPTNO) VALUES (1112,'박',40); --VIEW에 40번 부서직원 입력
 SELECT * FROM EMPvO;
 SELECT * FROM EMP WHERE EMPNO<2000;
 
 --VIEW의 제한조건
  --WITH CHECK OPTION 추가 : 뷰의 조건에 해당되는 데이터만 삽입, 수정, 삭제
  --WITH READ ONLY추가 : 읽기 전용 뷰
  
CREATE OR REPLACE VIEW EMPvO
 AS SELECT * FROM EMP WHERE DEPTNO=30
 WITH CHECK OPTION;
INSERT INTO EMPvO (EMPNO,ENAME, DEPTNO) VALUES (1113,'어',30);
INSERT INTO EMPvO (EMPNO,ENAME, DEPTNO) VALUES (1113,'어',40); --제한조건에 의해 오류
DELETE FROM EMPvO WHERE DEPTNO =20; --지워지지 ㅇ낳음
SELECT * FROM EMP;

--읽기전용 뷰(WITH READ ONLY 추가, WITH READ ONLY 추가하지 않은 경우)
CREATE OR REPLACE VIEW EMPvO
 AS SELECT * FROM EMP
 WITH READ ONLY;
SELECT * FROM EMPvO;
DELETE FROM EMPvO WHERE EMPNO<2000; --읽기전용뷰라서 오류
DELETE FROM EMP WHERE EMPNO<2000;
COMMIT;

CREATE OR REPLACE VIEW EMPvO --단순뷰에서도 INSERT 불가한 경우 : 뷰생성시 NOT NULL필드가 미포함 된 경우
 AS SELECT ENAME, JOB FROM EMP;
 SELECT * FROM EMPvO;
 INSERT INTO EMPvO VALUES ('홍길','MANAGER'); --EMP 테이블위 EMPNO(PK) 는 NOT NULL이라서 오류
 
 --(2)복합뷰 :2개 이상의 테이블로 구성한 뷰, 1개의 테이블로 가상의 필드를 이용한 뷰,DML문을 제한적으로 사용
 --①2개 이상의 테이블로 구성한 뷰
 CREATE OR REPLACE VIEW EMPvO
  AS SELECT EMPNO, ENAME, JOB, DNAME FROM EMP E, DEPT D WHERE E.DEPTNO =D.DEPTNO;
  SELECT *FROM EMPvO;
  INSERT INTO EMOvO VALUES (1111, '홍', 'MANAGER','SALES'); --복합뷰에서는 SELECT만 사용
 --②1개의 테이블로 가상의 필드를 이용한 뷰 (컬럼에 별칭을 사용)
 CREATE OR REPLACE VIEW EMPvO
    AS SELECT EMPNO,ENAME, SAL, SAL*12 YEAR_SAL FROM EMP;
 SELECT * FROM EMPvO;
 INSERT INTO EMPvO VALUES (1111,'홍',100,1200);-- 복합뷰에서는 SELECT만 사용
 
 CREATE OR REPLACE VIEW EMPvO(NO,ENAME, YEAR_SAL) 
    AS SELECT EMPNO,ENAME, SAL, SAL*12 FROM EMP;
    
CREATE OR REPLACE VIEW EMPvO(DEPTNO,AVG)
 AS SELECT DEPTNO, ROUND(AVG(SAL)) FROM EMP GROUP BY DEPTNO;
 SELECT * FROM EMPvO;
 --2.INLINE VIEW : FROM절의 서브쿼리를 INLINE VIEW라 하며, FROM 절에 오는 서브쿼리는 VIEW처럼 작용
  --ex.급여가 2000을 초과하는 사원의 평균 급여
  SELECT AVG(SAL) FROM EMP WHERE SAL>2000;
  SELECT AVG(SAL) FROM (SELECT SAL FROM EMP WHERE SAL>2000);
  --ex.부서 평균 급여보다 급여가 높은 사원의 사번,이름,급여,부서번호,해당부서의 평균급여(반올림)를 출력
  SELECT EMPNO,ENAME, SAL,DEPTNO, ROUND(SELECT AVG(SAL) FROM EMP E WHERE DEPTNO =E.DEPTNO)
  FROM EMP E 
  WHERE  SAL > (SELECT AVG(SAL) FROM EMP WHERE DEPTNO=E.DEPTNO);
 SELECT EMPNO, ENAME, SAL,DETPNO FROM EMP; --ⓐ
 SELECT DEPTNO ,AVG(SAL)AVGSAL FROM EMP GROUP BY DEPTNO; --ⓑ
 --ⓐ와ⓑ EQUI JOIN
 SELECT EMPNO, ENAME, SAL, A.DEPTNO, ROUND(AVGSAL)
  FROM EMP A,(SELECT DEPTNO, AVG(SAL) AVGSAL FROM EMP GROUP BY DEPTNO)B
  WHERE A.DEPTNO =B.DEPTNO AND SAL>AVGSAL;
  
--3.TOP-N 구문(TOP 1~10등, 11~20등 ,....)
    --ROWNUM(테이블로부터 가져온 순서)과 INLINE-VIEW를 이용한 TOP-N 구문
SELECT ROWNUM ,EMPNO ,ENAME FROM EMP;
SELECT ROWNUM, EMPNO, ENAME FROM EMP WHERE DEPTNO=20;

SELECT ROWNUM, ENAME, SAL FROM EMP;
SELECT ROWNUM ,ENAME,SAL --2 
    FROM EMP  --1
    ORDER BY SAL; --3
-- 1등~꼴찌 등수, 이름, 급여
SELECT ROWNUM RN,ENAME, SAL
    FROM(SELECT ENAME, SAL FROM EMP ORDER BY SAL); --DESC 반대로
    
--SAL을 기준으로 1~5등 
SELECT ROWNUM, ENAME, SAL
 FROM (SELECT * FROM EMP ORDER BY SAL)
 WHERE ROWNUM BETWEEN 1 AND 5;
--SAL을 기준으로 6등~10등
SELECT ROWNUM, ENAME, SAL
 FROM (SELECT ENAME ,SAL FROM EMP ORDER BY SAL)
 WHERE ROWNUM BETWEEN 6 AND 10;

--TOP-N
SELECT ENAME, SAL FROM EMP ORDER BY SAL; --1단계
SELECT ROWNUM RN ,ENAME, SAL 
 FROM (SELECT ENAME, SAL FROM EMP ORDER BY SAL); --2단계
SELECT ROWNUM, RN , ENAME, SAL 
 FROM (SELECT ROWNUM RN , ENAME, SAL
  FROM(SELECT ENAME, SAL FROM EMP ORDER BY SAL)) 
WHERE RN BETWEEN 6 AND 10;













