--Admin Dao
--1.로그인
SELECT * FROM ADMIN WHERE AID='3' AND APW='1';
-- (2) 로그인 후 세션에 넣을 용도 : admin aid로 dto 가져오기
SELECT * FROM ADMIN WHERE AID='admin';
--FILEBOARD DAO
INSERT INTO ADMIN (AID, APW, ANAME) VALUES ('리리','1','리리리');

--1.글목록
SELECT * FROM
  (SELECT ROWNUM RN, A.* FROM (SELECT F.*, MNAME FROM FILEBOARD F, MVC_MEMBER M
                              WHERE F.MID=M.MID 
                              ORDER BY FGROUP DESC, FSTEP) A)
  WHERE RN BETWEEN 2 AND 4;
--2.글갯수
SELECT COUNT(*) CNT FROM FILEBOARD;
--3.원글쓰기
INSERT INTO FILEBOARD (FID, MID, FTITLE, FCONTENT, FFILENAME, FGROUP, FSTEP, FINDENT, FIP)
  VALUES (FILEBOARD_SEQ.NEXTVAL, 'son','토트넘','난 공격수', 'a.docx', 
    FILEBOARD_SEQ.CURRVAL, 0,0, '192.168.0.31');
--4.HIT UP
UPDATE FILEBOARD SET FHIT = FHIT+1 WHERE FID=2;
--5.DTO가져오기
SELECT F.*, MNAME FROM FILEBOARD F, MVC_MEMBER M WHERE F.MID=M.MID AND FID=1;
-- 6. 글수정 (특정 bid의 bname, btitle, bcontent, bip 수정)
UPDATE FILEBOARD 
  SET FNAME = '홍길동',
      FTITLE = '글2-1(글3)-수정',
      FCONTENT = '본문수정',
      FIP = '127.0.0.1'
    WHERE FID=4;
--삭제
DELETE FROM FILEBOARD WHERE FID=1;
--답변글
SELECT *FROM FILEBOARD WHERE FID = 3;
UPDATE FILEBOARD SET FSTEP = FSTEP+1 WHERE FGROUP =2 AND FSTEP>0;
INSERT INTO FILEBOARD ( FID,MID,FTITLE,FCONTENT,FFILENAME ,FHIT,FGROUP,FSTEP,FINDENT,FIP) 
    VALUES (FILEBOARD_SEQ.NEXTVAL, 'gayun', '글1','',NULL,0,2,2,2,'192.1.1.1');
COMMIT;
SELECT * FROM FILEBOARD ORDER BY FGROUP DESC, FSTEP;

--MVC_MEMBER DAO
--(1)회원mid중복체크
SELECT COUNT(*) FROM MVC_MEMBER WHERE MID='go'; 
--(2)회원 memail중복체크
SELECT COUNT(*) FROM MVC_MEMBER WHERE MEMAIL = 'aaa@naver.com';
--(2)회원가입
INSERT INTO MVC_MEMBER (MID,MPW,MNAME,MEMAIL,MPHOTO,MBIRTH,MADDRESS)
    VALUES ('JENIE','1','제니','JENIE@naver.com','JENIE.jpg','1982/11/05','서울시');
--(3)로그인
SELECT * FROM MVC_MEMBER WHERE MID='JENIE' AND MPW ='1';
--(4)mid로 멤버 dto가져오기 (로그인 성공시 session에 setAttibute하기 위함)
SELECT * FROM MVC_MEMBER WHERE MID='JENIE';
--(5)회원정보수정 (특정mid의 정보 수정)
UPDATE MVC_MEMBER 
    SET MPW = '1',
        MNAME = '제니',
        MEMAIL ='JENIE@naver.com',
        MPHOTO ='JENIE.jpg',
        MBIRTH = '1982/11/05',
        MADDRESS = '뉴욕시' 
    WHERE MID = 'JENIE';
--(6)회원리스트(top-n구문)
SELECT * FROM (SELECT ROWNUM RN , A.* FROM (SELECT * FROM MVC_MEMBER ORDER BY MNAME)A)WHERE RN BETWEEN 1 AND 3;
--(7)회원수
SELECT COUNT(*) CNT FROM MVC_MEMBER;
--(8)회원탈퇴
DELETE FROM MVC_MEMBER WHERE MID ='JENIE';
ROLLBACK;
COMMIT;




























