--DAO에 쓸 SQL
--1.글 목록(글 그룹 최신글이 위로)
SELECT * FROM BOARD ORDER BY BGROUP DESC;
--1.글 목록(startRow 부터 endRow까지 리스트)
SELECT * FROM BOARD ORDER BY BGROUP DESC;
SELECT ROWNUM RN, A.* 
  FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC) A; -- TOP-N구문 전단계
SELECT *
  FROM ( SELECT ROWNUM RN, A.* 
         FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC) A )
  WHERE RN BETWEEN 21 AND 30; -- TOP-N구문 (DAO에 들어갈 QUERY)
--2.전체 글 갯수
SELECT COUNT(*) CNT FROM BOARD;
--3. 원글쓰기 - 작성자 ,글제목, 본문, 이메일, 비번, IP (BGROUP 글번호, BSETP은0 , BINDENT는 0)
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BEMAIL, BPW, BGROUP, BSTEP, BINDENT, BIP) 
            VALUES (BOARD_SEQ.NEXTVAL, '홍','제목1','냉무',NULL,'111',BOARD_SEQ.CURRVAL, 0,0,'192.168.5.4');
--4.BID로 조회수 1 올리기 (글상세보기시 필요)
UPDATE BOARD SET BHIT = BHIT + 1 WHERE BID=1;
--5.BID로 DTO가져오기 (글수정FORM , 답변글쓰기 FORM)
SELECT * FROM BOARD WHERE BID = 1;
--6.글수정(작성자, 글제목, 본문, 이메일, 비번, IP수정)
UPDATE BOARD 
    SET BNAME  = '홍길동',
        BTITLE = '바꾼제목',
        BCONTENT = '바꾼본문',
        BEMAIL = 'H@H.COM',
        BPW = '111',
        BIP = '127.0.0.1'
    WHERE BID ='1';
--7. 글삭제(비번을 맞게 입력한 경우만 삭제)
COMMIT;
DELETE FROM BOARD WHERE BID =1 AND BPW ='111';
ROLLBACK;
SELECT * FROM BOARD ORDER BY BGROUP DESC;


